// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA553np3TvR19VDqij2I1WdXHT9I8nm1Kg',
    appId: '1:1021708879332:web:5f9ae0dae9dd0148ba73f1',
    messagingSenderId: '1021708879332',
    projectId: 'soynote-aad8d',
    authDomain: 'soynote-aad8d.firebaseapp.com',
    storageBucket: 'soynote-aad8d.appspot.com',
    measurementId: 'G-HGCYDPJ85L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8w19ZOKO6gY1MX3Xw6bB7yH4wT4kyz10',
    appId: '1:1021708879332:android:8e571f76d9c02e47ba73f1',
    messagingSenderId: '1021708879332',
    projectId: 'soynote-aad8d',
    storageBucket: 'soynote-aad8d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0NaKRwLLRUe2nscxDCwVFXewsQRIbVmM',
    appId: '1:1021708879332:ios:6ba0f57e4db11d89ba73f1',
    messagingSenderId: '1021708879332',
    projectId: 'soynote-aad8d',
    storageBucket: 'soynote-aad8d.appspot.com',
    iosBundleId: 'com.example.soynote',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0NaKRwLLRUe2nscxDCwVFXewsQRIbVmM',
    appId: '1:1021708879332:ios:0048f6cf9c0ddeedba73f1',
    messagingSenderId: '1021708879332',
    projectId: 'soynote-aad8d',
    storageBucket: 'soynote-aad8d.appspot.com',
    iosBundleId: 'com.example.soynote.RunnerTests',
  );
}
